nengo/nengo-gui

- nengo_viz/static/viz_value.js
Since we were "or"-ing together values to determine the defaults,
the default value would be used if the inputs were zero, since
zero evaluates as false. Now checking whether they're `null`.
> Fixed bug where maxy or miny ignored if zero

- nengo_viz/components/netgraph.py
In some numpy versions, the object returned by Node.size_out is a zero-dimensional array, rather than an int.  This causes problems when serializing, so we need to cast it to an int just in case.
> Fix for obj.size_out not being an int in some numpy

- nengo_viz/components/netgraph.py
The switchfrom .items() to nengo.utils.compat.iteritems() wasn't
tested well enough here.  The loop changes the dictionary, and
iteritems() really doesn't like that.  This wasn't a problem with
the .items() approach, since it's only ever changing the item
it's on in the loop.  The fix here is to duplicate the dictionary.
> Fixed bug in reload re:iteritems

- nengo_viz/components/netgraph.py
- nengo_viz/components/pointer.py
- nengo_viz/static/viz_netgraph_item.js
Netgraph items now get output list from Module object and passes it to client to use (client only uses first item for now -- waiting for the graphical overhaul branch to be merged before handling multiple possible outputs).
Client passes output name back to server when generating pointer graphs.
> Draft version of Pointer graphs supporting non-default outputs

- nengo_viz/components/netgraph.py
Right now if you collapse a sub-network and then re-expand it, the internal items do not re-appear.
This bug was introduced by the reload system, since it tries to avoid re-creating things that already exist, but when collapsing a network it doesn't realize that those items no longer exist on the client.
> Fixed subnetwork expansion after collapse

- nengo_viz/components/netgraph.py
This addresses #196 and simply adjusts the top-level autolayout such that takes into account the global pan/zoom state.
> Made autolayout use the full available space

- nengo_viz/swi.py
When a websocket is closed, that event now gets noticed so the VizSim can be shut down.
> Fixed detecting closed websockets

- nengo_viz/server.py
Follows up on @hunse 's comments in #188 that were missed before it was merged.
Basically just removes a redundant ```component.finished()``` and uses a ```break``` instead of a ```return```.
> Tiny cleanup to websocket loop

- nengo_viz/components/netgraph.py
- nengo_viz/components/pointer.py
- nengo_viz/components/raster.py
- nengo_viz/components/value.py
- nengo_viz/components/xyvalue.py
- nengo_viz/viz.py
Popping the first item repeatedly is O(n^2). (http://stackoverflow.com/questions/195625/what-is-the-time-complexity-of-popping-elements-from-list-in-python) This change makes `update_client` O(n).
Also made the lock safer with a context-manager. Previously, an exception in between would have caused a deadlock.
> Optimize update_client, lock safety

- nengo_viz/disposable_js.py
- nengo_viz/static/viz_modal.js
- nengo_viz/static/viz_top_toolbar.js
While we won't do this, it makes it possible to make multiple modals. The major advantage here is just that the Javascript code looks more idiomatic.
The main reason I did this was because info_body was being used to clear the body, which is overkill (and adds divs we don't want). So I also added a clear_body function. And a text_body function, which the reset modal now uses (it is resettable right?)
I know that this'll make merging #186 and #195 a bit more complicated, but the history of those branches needs to be fixed up anyhow (which I'm happy to do!)
> Make Modal a class instead of singleton

- nengo_viz/server.py
This caused a bug where multiple threads trying to update the client caused a crash for the semantic pointer plot.
> Closed the websocket of a component after it is removed. 

- nengo_viz/viz.py
If nengo_viz is inventing a label, it used to do something
like "model.net.subnet.input". All of the stuff before the
last "." is redundant, since that's already shown by
nesting inside the visual display.  So this change cuts it
down to just "input".
> Removed extraneous path from default labels

- nengo_viz/static/viz_modal.js
- nengo_viz/static/viz_pointer.js
- nengo_viz/static/viz_slider.js
- nengo_viz/static/viz_value.js
- nengo_viz/static/viz_xyvalue.js
This was branched off of a merge of graphics-overhaul and info-window.  It changes all the value setting and range setting dialogs to bootstrap modals.  It doesn't currently do validation. I'll branch this and do validation in a separate PR.
> Modal inputs

- nengo_viz/swi.py
Addresses #222 and hopefully fixes it.
Without properly closing the connection it seems that Firefox treats it as an unexpected close due to an error which increases a delay before new websocket connections are allowed.
> Perform a proper closing handshake for websockets.

- nengo_viz/static/viz_netgraph.js
- nengo_viz/static/viz_viewport.js
Unsatisfied with all attempts to fix the zooming, I did some research on my own. The first things on SO you find on this are actually outdated or the people don't know what they are talking about. The wheel event delta values are actually not as widely inconsistent as it may appear in the first place. Though there are some inconsistencies across browserse, platforms, and devices, they are in a sensible range and we don't have to achieve exactly the same result for any combination as long as it feels ok for any combination.
I tested this PR with
* Chrome, Firefox, and Safari on OS X
* Chrome, Firefox in a Windows VM
Trackpad zooming on OS X feels super smooth. :sparkles: Mouse wheel works well (a bit better in Firefox I think). On Windows it didn't feel as nice, but still ok/usable. The …
> Use delta value in zooming.

- nengo_viz/components/action.py
This used to happen, but was lost in the merge with the undo stack.
There's also a commit here to change the logic so we don't run the layout algorithm three times in immediate succession.
> Made autolayout use full available space again

- nengo_viz/components/sim_control.py
- nengo_viz/viz.py
On Windows, the paths include backslashes, which
weren't being escaped in the string, so they were bring
interpretted as special escape characters
> Fixed filename display on Windows

- nengo_viz/components/sim_control.py
- nengo_viz/monkey.py
- nengo_viz/viz.py
This now handles some of the cases of weirdnesses that can happen when loading
- Any exception is printed to the console and we recover gracefully.  In a future PR this exception should be sent to the browser and displayed somehow
- If the script creates a Simulator object (either nengo.Simulator or nengo_ocl.Simulator), it stops executing the script at that point (before build)
- If the script creates a Viz object, it stops executing at that point
This means we no longer need ```if __name__ == '__main__':``` protection in the example scripts (issue #101).
> Handle loading bad files

- nengo_viz/static/viz_netgraph_item.js
This is meant to address #244 and #141 .  It moves NetGraphItems to the front whenever they are dragged.
However, it's not yet a perfect solution.  It currently does not move expanded Networks to the front, since that would put them on top of any child networks that are currently expanded.  I need to add some logic for that.
> Move items to front on drag

- nengo_viz/swi.py
This solves problems resulting in the frequent 'x zombie threads killed' message on shutdown (cp. PR #221). See commits (and commit messages) for details. Essentially, `close()` on a socket might take until the object is garbage collected. For an instant close `shutdown` has to be called beforehand, but that can lead to exceptions because threads are suddenly missing their sockets, so that has to be taken care of. And lastly, their where iterations over a list while it was modified. That's never a good idea.
Time to sleep now ... :sleeping:
> Timely thread shutdown

- .gitignore
Did some Windows testing with vagrant and don't want to have these files always show up in the status report.
> Add Vargant stuff to .gitignore.

- nengo_viz/static/viz_modal.js
- nengo_viz/static/viz_tooltips.js
Some text edits on the details dialog tooltips.  Changed from the blue glyph icon to a small blue text question mark (less obtrusive?).
Still to do:
- Add tooltips to network details
- Add tooltips to the 'tuning curve' and 'response function' graphs
> Text edits and changed details icon

- nengo_viz/monkey.py
When it tries to import nengo modules for the monkey-patching,
it might get something other than an ImportError if that module
is installed wrong.  For example, nengo_ocl on my machine
currently raises an AttributeError.  This change causes it to
handle any error raised.
> Handle any sort of error on backend import during monkeypatch

- nengo_viz/static/viz_sim_control.css
- nengo_viz/static/viz_top_toolbar.css
Someone commented that the new toolbar style was hard on the eyes because the light grey bleeds into the backgound. I think, this was mainly due to the light shadow which I made stronger now and which gives a better separation.
> Restyle toolbar shadows.

- nengo_viz/__init__.py
- nengo_viz/examples/default.py
- nengo_viz/main.py
- nengo_viz/server.py
- nengo_viz/static/viz_top_toolbar.css
- nengo_viz/viz.py
- setup.py
This should act like nengo_gui, in that you can specify a file to open, otherwise it will open a default.py file.
One change from nengo_gui is that the file browser shows files from where you ran the script, and in addition it also shows the built-in examples folder.  This way people have access to the built-in examples as well as a more typical file browsing in their local folders.
> Added 'nengo_viz' script to start the visualizer

- nengo_viz/static/viz_netgraph_item.js
All NetGraphItems now have a transparent bounding box
around them, and that bounding box handles resize events.
For Nodes and Networks, the shape (a rect) also handles
resize events.  For Ensembles, the shape (6 circles) does not handle
resize, since it's already a small enough target.
> Fixed resizing issues

- nengo_viz/static/main.css
- nengo_viz/static/viz.css
- nengo_viz/static/viz_menu.css
- nengo_viz/static/viz_modal.css
- nengo_viz/static/viz_netgraph.css
- nengo_viz/static/viz_slider.css
- nengo_viz/static/viz_slidercontrol.js
Seems to work on firefox, chrome and safari as expected.  No selectable text on netgraph/components, text cursor in modals input boxes.  No interference on resizing. I found the magic 'pointer-events:none' css which makes this easier.
> Fixing css styles for cursors

- nengo_viz/components/action.py
This change has been made on the server side, because it wasn't possible to implement it on the client side since we do not have access to the parent 'node' on the client side.
> Removing the old slider when making a new one

- .gitignore
- examples/net.ipynb
- nengo_viz/components/netgraph.py
- nengo_viz/components/sim_control.py
- nengo_viz/ipython.py
- nengo_viz/server.py
- nengo_viz/static/viz_top_toolbar.css
- nengo_viz/static/viz_top_toolbar.js
- nengo_viz/swi.py
- nengo_viz/viz.py
Opening this PR for people to take a look at and try out. It seems to be working quite well already, but there are a few more things which should maybe addressed.
This allows to embed the nengo_viz visualization easily in IPython notebooks. Just do
```python
from nengo_viz.ipython import IPythonViz
IPythonViz(model)
```
Assigning the `IPythonViz` object to a variable and displaying it multiple times should work (it's like opening multiple tabs for nengo_viz). Different `IPythonViz` objects should be able to coexist.
Potential things to do:
> Embedded visualization in IPython notebook

- nengo_viz/components/raster.py
This is a very temporary fix on the server side to prevent the exception being thrown right now. This code should later be removed from the server side and the fix should be made on the client side (this would require passing the information regarding the neuron type of an ensemble to the client).
The spike plot will still show up , but there will be no spikes displayed in direct mode
> No Spikes shown for an ensemble in direct mode

- nengo_viz/server.py
- nengo_viz/swi.py
Fixes #222.
I think, with this PR all websocket connections are always properly closed no matter which side initiates the close. Because of the organization of the server code, this patch is not as straight-forward as I'd like it to be. In fact, the organization of the server code seems a bit convoluted without a good separation of concerns. But refactoring it would be a slightly larger job. It might be complicated by the base Python classes which probably where to designed with prolonged connections (websockets) in mind.
> Properly close websockets on server shutdown.

- nengo_gui/static/hotkeys.js
- nengo_gui/static/netgraph.js
Here's a quick fix for the spacebar problem.
It's not perfect because you can't click on the NetGraph to change focus (the text editor keeps the focus).  But if you click on the top or bottom bar, hotkeys will now work as expected.
> Fix the spacebar problem with the editor

- nengo_gui/monkey.py
stack traces are slightly different in Python 3.  Without this fix, certain types of syntax errors would crash the server.
> Fixed error message handling on Python 3

- nengo_gui/components/sim_control.py
- nengo_gui/server.py
- nengo_gui/static/sim_control.js
- nengo_gui/static/top_toolbar.js
- nengo_gui/viz.py
With the old system, we would occasionally get weird duplication bugs where things mostly don't work and there are two copies of the NetGraph (and other components).  These were accompanied by lots of "Error finding label" bugs.
This PR changes the load system so that instead of a two-part process where the internal Viz is updated and then the client does a reload, now the reloading is done in the actual swi page request itself (i.e. after the reload).  This means that we no longer have a period of time where the old page is connected to the server with the new content.  I believe the bug were due to information being passed to the client about the new page before the reload happens.
> Refactor reload to fix reloading problems

- nengo_gui/static/netgraph_item.js
They used to be sized based on the size of the component
that the graph is about.  Now they are generated at a fixed
200px by 200px size. (Sliders are at half that width).
> Created graphs now appear with a specific size

- nengo_gui/components/ace_editor.py
- nengo_gui/viz.py
This at least stops the editor from dying when you try to save a read-only file.  But there should also be some sort of visual feedback that it didn't save.
> Handle IOErrors when saving file

- nengo_gui/static/modal.js
- nengo_gui/static/netgraph.js
- nengo_gui/static/netgraph_item.js
- nengo_gui/static/top_toolbar.js
This is a bit of an experiment to see what it looks like when expanded networks are transparent, with just the border shown. I've been thinking for some time that this is the right way to render networks, but it's hard to convince even myself without actually seeing it. Having seen it now, I do like it, but will leave it to the consensus.
Note that this is still considered a WIP because I just did the minimal implementation in order to get it to work; the code needs to be looked at by someone more knowledgable with this part of the code base. Also, if the consensus thinks this is good, then we can remove some additional existing code; for example, we could remove `compute_fill` because we don't have to worry about the infinite depth issue.
A network is either collapsed (grey), or expanded …
> Add option to make expanded networks transparent

- nengo_gui/monkey.py
- nengo_gui/server.py
Missing this exception has caused the "editor stops updating anything" bug that we currently work around by reloading the page.
> Handle exceptions when processing websocket msgs

- nengo_gui/monkey.py
As @jgosmann pointed out to me:
>  exc_traceback is deprecated since version 1.5(!).
So this switches to the more modern (and thread-safe) approach.
> Switched sys.exc_traceback to sys.exc_info

- nengo_gui/static/sim_control.js
- nengo_gui/static/slider.js
This handles slider positions when the simulation resets (so that the sliders don't end up staying wherever they got left in the previous simulation).  Handles both constant sliders and callable sliders.
Fixes #365
> Reset slider positions on simulation reset

- nengo_gui/components/netgraph.py
Fixes #398 and #406
It was supposed to be detecting an object changing its nengo class, but that update was sent to the javascript *after* the new objects were created, confusing things.  This change fixes that and also detects Nodes changing to passthrough Nodes (and vice-versa).
> Handle class changes when code changes

- nengo_gui/components/slider.py
The slider resetting system wasn't working in the
case where the simulation was being reset due to new graphs
being created.  I believe this is at least part of the problems
noted in https://github.com/nengo/nengo_gui/pull/426#issuecomment-112223850
To replicate, run a model with a graph and a slider.  Move the slider around a bit and leave it at a non-zero value.  Now make a new graph.  Hit play again.  Without this fix the Node will continue to output the old value, even though the slider moves back to its original value.  With this fix the Node's output value will be reset.
> Makes sliders reset on simulation restart

- nengo_gui/components/value.py
This reduces the amount of computation in javascript, and it greatly improves the look of nengo_spinnaker plots (since they're not guaranteed to sample at a regular rate, so doing the filtering after sampling is a bad idea).
> Filtered value plots in nengo, not javascript

- nengo_gui/components/xyvalue.py
- nengo_gui/static/xyvalue.js
This applies the #461 fix (filtering in nengo, rather than in javascript) to XY plots, for consistency
> Prefiltered xy plots as well

- nengo_gui/static/hotkeys.js
- nengo_gui/static/modal.js
Built in a flag to see if the modal is open or not. If it's open, hotkeys are deactivated.
Fixes #385
> deactivate hotkeys when modal is active

- nengo_gui/components/__init__.py
- nengo_gui/components/ace_editor.py
- nengo_gui/components/action.py
- nengo_gui/components/component.py
- nengo_gui/components/netgraph.py
- nengo_gui/components/pointer.py
- nengo_gui/components/raster.py
- nengo_gui/components/sim_control.py
- nengo_gui/components/slider.py
- nengo_gui/components/value.py
- nengo_gui/components/voltage.py
- nengo_gui/components/xyvalue.py
- nengo_gui/config.py
- nengo_gui/page.py
- nengo_gui/server.py
- nengo_gui/static/nengo.js
- nengo_gui/static/netgraph.js
This gets rid of the Component/Template distinction that complicates the server-side code.
Now that Page and GUI have been reorganized, the entire reason for Templates is gone.  They were originally there because the config file was shared across multiple Viz objects, and so the config file was processed before the actual Components themselves existed.  So the config file actually configured these Component Templates, and the Components (when they were created when a page was actually generated) got their information from the Templates.
But now we don't look at the config file until after the Page is being created, so all that indirection is unnecessary, and so this PR gets rid of the Templates.
Some notes:
- This slightly changes the .cfg file format, in that it is no longer necessary to …
> Remove component templates

- nengo_gui/static/2d_axes.js
- nengo_gui/static/value.js
Instead of letting d3 automatically generate ticks as it want, Enforce that it labels the min and max values of the value plot range.
Fix #261
> Y axis labels for value plots

- nengo_gui/static/raster.js
- nengo_gui/static/xyvalue.js
When I merged #502 I didn't notice that it broke the labelling and layout for the raster plots and the xy plots.  So this is a quick fix to make those look right again.
This is a small change and fixes a pretty big bug in master, so I'll merge it quickly and if there are discussions about a better way of doing this fix, we can do that in a separate PR.
> Fixed axes on raster and xyvalue plots

- nengo_gui/static/2d_axes.js
- nengo_gui/static/xyvalue.js
The axes display for XY plots is currently very wrong due to changes introduces in #502 and an attempted (but incomplete) fix in #511.  This returns it to the original display where the lines are always crossed through the middle.
> Fixed broken XY plots

- nengo_gui/components/action.py
- nengo_gui/components/component.py
- nengo_gui/components/netgraph.py
This addresses #425 and a variety of other fixes.  Basically, if anything that's set in the constructor for a Component is changed, then we need to recreate that Component on the client side.
This fixes the following:
- if you change the dimensionality of a Node, the number of sliders will change
- if you change the dimensionality of an Ensemble or Node, the number of lines in the value graph will change
- if you change from 1 dimension 2 dimensions, the option to show an XY Value plot should appear (or disappear)
- if you add a ```_nengo_html_``` attribute to your Node, then the ```HTML``` plot option should appear.
- changing the label on an item should cause that label to change in the graphs
> Improved updating of display as components change

- nengo_gui/components/value.py
- nengo_gui/static/value.js
This might finally fix #357 !   We should no longer have those value plots that lose their data when the simulation is running quickly.
The fix basically involves sending all the pending data at once, rather than sending a packet for every time step.
> Fixed value plots being behind on their data

- nengo_gui/static/2d_axes.js
The old way returned zero a lot in Firefox (tested on 39.0, Windows).  This meant that the ticks would take up exactly zero space, making them unreadable.
> More robust way to compute bounding box for graph ticks

- nengo_gui/main.py
Allow user to specify if they want a new browser window to pop-up after starting the server. This is specified by using --no-browser (or --browser). True by default
> Choose if new browser window should be opened

- nengo_gui/examples/tutorial/13-oscillators.py
was just working through tutorials and noticed that in the comments y0 was used instead of x1 (pretty sure it's supposed to be x1 and this was just missed in changing it over from y0)
> changed y0 to x1

- nengo_gui/page.py
This ensures nengo_gui doesn't crash if Page.execute()
is never called (as is the case when manually starting
up the gui with a pre-defined model)
> Fix page initialization

- nengo_gui/components/sim_control.py
The speed calculation in the bottom-left is often hysterically wrong (most noticeably when running nengo_spinnaker).  This fixes the calculation and means that when using nengo_spinnaker the speed very clearly is at 1.00x realtime.  :)
> Fixed calculation of simulation speed

- nengo_gui/page.py
I broke nengo_gui.  It was in a state where it would never notice that it had successfully executed a script, other than the first time it ran.
> Fix completely broken page update due to #570

- nengo_gui/namefinder.py
This was preformed for lists of objects, but not for single objects.
Amazingly, this resolves #563
> Added check for exiting items in NameFinder

- nengo_gui/modal_js.py
Python3 support was broken since Aug 26 due to
38192511b22bbcb35ebabb3904cee039e4a54021
> Made import relative so that it works in Python3 again

- nengo_gui/static/main.css
Addresses #599 
This works in Chrome and Safari on Mac; Please check other OSs.  Be sure to check that sliders are still editable, and that ctrl/cmd-a works in the editor window.
On Mac, cmd-a used to select many elements of the GUI that we didn't want selected.
> Fixes accidental selection in browser

- nengo_gui/static/nengo.js
Current method doesn't work for long labels, because I forgot to include the text as part of the label class...
> Fix label svg sizing

- CONTRIBUTORS.md
- nengo_gui/components/pointer.py
Fixes an error that occurs when, e.g., running `25-spa-parse.py` with Python 3.
Coincidentally, I can't select or copy text from the error pane below the code in Nengo GUI (Firefox 42.0, Arch Linux); is that a bug?
> Fix Python 3 `zip` error

- nengo_gui/components/netgraph.py
- nengo_gui/layout.py
The gui currently crashes if you try to use the new syntax for learning rules.  This quick change just updates things so that it handles them exactly like it did the old syntax.  In some future PR we probably would want a visual indication of the learning rule, but this at least lets people work with learning rules and the new syntax.
> Handling of new-style LearningRule Connections

- nengo_gui/components/ace_editor.py
- nengo_gui/static/ace.js
- nengo_gui/static/components/netgraph.js
- nengo_gui/static/config.js
- nengo_gui/static/modal.js
- nengo_gui/static/top_toolbar.js
- nengo_gui/templates/page.html
- nengo_gui/tests/test_configuration.py
The bulk of the logic is in `static/config.js`. So far we only persist the 4 configuration options accessible through the gear icon in the top toolbar, but we can add more things easily.
Addresses issue #375.
> Persist configuration options to local storage

- nengo_gui/components/netgraph.py
This typo was causing us to remove and rebuild every item in the network whenever any object was removed.  In terms of efficiency per character, this has got to be a record breaking optimization :sunglasses:.
> Fix remove logic

- nengo_gui/static/ace.js
- nengo_gui/static/config.js
- nengo_gui/static/hotkeys.js
- nengo_gui/static/modal.js
- nengo_gui/static/top_toolbar.css
- nengo_gui/static/top_toolbar.js
- nengo_gui/templates/page.html
This is just a version of #651 without the horrible mess of a rebasing I accidentally did to it.
> Toggle for auto-updating from code editor

- nengo_gui/components/pointer.py
If the .vectors attribute of a vocab object is modified to include one or more vectors with a very large norm, the dot products used to calculate the similarities depicted in semantic pointer plots can get big. Currently, the gui assumes these dot products are single digit, and accordingly gets confused and makes plots with extra numbers in them if they aren't. This pull request fixes this problem (issue #438) by clipping any dot products above 9.99.
> Prevents random numbers from appearing in SP cloud plot.

- nengo_gui/static/modal.js
Addresses #631 
When entering values for sliders or changing their range, you can now optionally press tab to go to the next value instead of typing in the commas. This will automatically put the comma in for you, and will automatically fill in the previous value for an index if you leave it blank and press tab.
> allowing tabbing to set multiple values for input box

- nengo_gui/static/components/netgraph.js
- nengo_gui/static/components/netgraph_conn.js
- nengo_gui/static/components/netgraph_item.js
This addresses #276 (lag on firefox when dragging around large networks).  It's still a little bit choppy when dragging a big network around, but significantly improved from what it was like before.
The first improvement comes from only updating the minimap when it is being displayed.  Before we were updating it all the time, so we were effectively doing twice as many updates/redraws as necessary.
The most significant change to the code-base here is that I modified the minimap logic so that the main object takes care of keeping the minimap object up to date (rather than the old method, where the overall netgraph took care of updating both the main objects and the minimap objects).  This means that there is only one place where we need to check if the minimap is open, rather than having to …
> Optimize display

- nengo_gui/components/ace_editor.py
- nengo_gui/static/ace.js
- nengo_gui/static/top_toolbar.css
- nengo_gui/static/top_toolbar.js
- nengo_gui/tests/test_save_as.py
Here's a first version of save-as.  The current functionality is tied to clicking on the file name, which I don't particularly like, but seems okay for now until we rethink the top toolbar.
If you try to rename to an existing filename, it will give an error message.  If you try to rename to an invalid file name, it will also give an error message.
> Click on file name to save-as

- nengo_gui/config.py
A recent merge in Nengo changed the constructor for nengo.params.Parameter.  This causes the entire GUI to crash horribly.
This change fixes the GUI to work.  It is backwards-compatible so will work with both the recent changes and with the old (release) version.
> Fix GUI due to change in Nengo

- nengo_gui/config.py
Pull requires #695 was an emergency fix to repair a broken nengo_gui build ( #694 ) due to a change in nengo.  It got merged immediately, but didn't have a code review about whether it was the right way to fix it.  This is the PR for actually reviewing #695 and doing it better.
@jgosmann has already pointed out that it should be ```except TypeError:``` rather than ```except:```, so that change is here.  Any others?
> Improved the nengo.params fix

- nengo_gui/static/components/netgraph_item.js
Fix for #703. Just dropping the `this` from the call to `ng`.
> Fix#703 ensemble resizing

- nengo_gui/components/netgraph.py
- nengo_gui/components/slider.py
@celiasmith noticed that you couldn't make sliders when a node had a `Process` as the node output. With this commit, sliders now work properly. I think a few slider bugs might also be fixed with this as I reduced a bit of code duplication, but that's just a guess.
This PR also changes how `node.output` is overridden for all other node output types. The changed version uses processes, so this change breaks compatibility with Nengo 2.0.x, so that should be kept in mind when determining when to merge this commit (and is also why TravisCI fails on this branch).
The new `OverriddenOutput` should be slightly faster in some cases because the (former) `data` list is now a NumPy array where `np.nan` indicates that the value should not be overridden. This array is only modified, not copied, so we …
> Enable sliders on nodes with process outputs

- nengo_gui/static/ace.css
- nengo_gui/static/ace.js
- nengo_gui/static/config.js
As an alternate approach for #626 here I've just completely removed console hiding.  
The console is always there, but you can make it smaller (and it doesn't change its size on its own based on message length).  Also, the size of the console is now persistent, so you can shrink it away when you don't want to worry about it, which is almost the same as hiding it (but doesn't require memorizing a hotkey or having some visual indication as to how to get it back).
I'm mostly putting this PR out there for feedback, in comparison to @studywolf 's #698, which provides a hot key to toggle auto-hiding.
I think this PR is simpler and cleaner, but it'd be good to get some other feedback.
> Remove console hiding

- nengo_gui/page.py
This fixes #699 and possibly #711 
At the moment, nengo gets a bit confused if a separate thread ```close```s a Simulator while it is still in the middle of a ```run()``` call.  This just reorganizes nengo_gui slightly to make sure the close gets called after the run.
> Stop sim.close() from happening during sim.run()

- nengo_gui/exec_env.py
- nengo_gui/page.py
The changed to Nengo Exceptions meant that the logic for finding the line number of the error was going wrong.  The new code explicitly marks the executed code rather than using the default ```<string>```.
> Fixed error message reporting

- nengo_gui/exec_env.py
My rushed fix from #714 missed a case, causing it to fail to determine line numbers for indentation errors.  This fixes that fix.
> Fixed error line computing error for indentation errors

- nengo_gui/components/sim_control.py
I'm not sure why actual_model_dt can be zero on spinnaker,
but I've seen it happen once so we may as well check for it.
> Fix dt==0 problem on nengo_spinnaker

- nengo_gui/components/slider.py
Current nengo_spinnaker doesn't handle Processes for input Nodes, so that breaks sliders from working.  For now, this fix just calls make_step on the Process and uses that resulting function if it's running on nengo_spinnaker.  In the future, there should be some way of asking a backend if it supports Processes (and we should get Processes working on nengo_spinnaker), but in the meantime this lets things work.
> Fixed sliders on nengo_spinnaker

- CONTRIBUTORS.rst
- LICENSE.rst
- README.rst
- nengo_gui/__init__.py
- nengo_gui/conftest.py
- nengo_gui/gui.py
- nengo_gui/main.py
- nengo_gui/server.py
- nengo_gui/version.py
- setup.py
This does a few minor things in preparation for the 0.2 release. Specifically:
- Convert `.md` files to` .rst` for consistency with Nengo and README.rst.
- Update license with minor nits found by Pete (as done in Nengo)
- Update version numbering scheme to conform to PEP440
- Edit some parts of the README
- Make a `nengo` script and deprecate the `nengo_gui` script
See individual commits for more information.
**Before this PR is merged** the following contributors need to sign ``CONTRIBUTORS.rst``, as we missed them when merging pull requests.
To sign the file, please make a commit adding yourself to the ``CONTRIBUTORS.rst`` file. That commit can be pushed to this branch (or if you prefer, you make a separate branch and PR for it).
Please read that file, as well as the assignment …
> Fixes for 0.2 release

- nengo_gui/static/top_toolbar.js
A variable with the wrong name was causing this option to be cleared whenever the config menu "Cancel" button was clicked.
I believe this is the source of the bug where every now and then someone would find that their network diagram suddenly stopped being updated.
> Fixed typo causing autosync to clear

- nengo_gui/components/ace_editor.py
- nengo_gui/static/ace.js
- nengo_gui/static/top_toolbar.css
Addresses #785.
Colors the save icon red until the server confirmed the save. If the save fails the icon will stay red as indicator of the failure. This should improve the current state of affairs, though it's not a perfect solution:
* It would be best if the save would not fail.
* If it fails a descriptive error message would be better because with the red background it might not be clear what it means.
* The button will give a short red flash on a successful save.
Addressing these points is not trivial due to the asynchronous implementation. If we'd rely on the server to notify the client of the failure that notification might never be received. So we have to treat the save as failed until confirmed otherwise.
> Add an indicator for failed save.

- nengo_gui/guibackend.py
WebSockets could end up hanging in the hot loop waiting for further
messages.
> Ensure proper WebSocket shutdown.

- nengo_gui/server.py
Safari requires the line ending to be \r\n, other forms are
disallowed.
Fixes #880.
> Fix websocket upgrade in Safari.

- nengo_gui/exec_env.py
- nengo_gui/page.py
- nengo_gui/static/ace.js
A number of new users have asked questions like this one:
https://forum.nengo.ai/t/how-to-see-the-plots/282
where they are taking Nengo examples and pasting them into the GUI (rather than running them in a Python interpreter). 
This PR gives a more informative error message when this happens, and directs them to a web page that gives more detail.
There are 2 commits here -- the first one gives the error message, and the second one makes the link work.  I've separated them like that because it's a bit annoying how I'm getting a HTML from the server to the client -- we used to assume that this was always text, not HTML.  If someone has a better way to do this, that'd be good too.
> More informative message when making a Simulator in the GUI

- nengo_gui/layout.py
The following model breaks `nengo_gui`:
```python
import nengo
model = nengo.Network()
with model:
stim = nengo.Node([0])
a = nengo.Ensemble(n_neurons=50, dimensions=1)
b = nengo.Ensemble(n_neurons=50, dimensions=1)
nengo.Connection(stim, a)
conn = nengo.Connection(a, b[0], learning_rule_type=nengo.PES())
stim2 = nengo.Node([0])
nengo.Connection(stim2, conn.learning_rule)
```
This produces
```
Traceback (most recent call last):
File "c:\users\terry\documents\github\nengo_gui\nengo_gui\guibackend.py", line 230, in ws_default
component.update_client(self.ws)
File "c:\users\terry\documents\github\nengo_gui\nengo_gui\components\netgraph.py", line 399, in update_client
self.expand_network(network, client)
File "c:\users\terry\documents\github\nengo_gui\nengo_gui\components\netgraph.py", line …
```
> Fix learning rules on sliced connections

- CHANGES.rst
- nengo_gui/guibackend.py
- nengo_gui/server.py
This implements support for IPv6 with a dual stack solution supporting IPv4 and IPv6 at the same time. In theory this also allows to listen on multiple ports or network interfaces at the same time. But this is not exposed within `main.py`, so the `nengo` command only allows to listen on all `localhost` addresses (no password protection) or all interfaces (with password protection). I assume this to be fine in almost all cases and do not intend to change this as long as there are no such requests because it would complicate the interface without need.
Due to the current implementation of the WebSocket origin checking the GUI does not support access by IP address (e.g. `127.0.0.1` or `[::]`), except when started with a password.
Addresses #21.
> Add dual stack IPv6 support.

- nengo_gui/components/voltage.py
The voltage plot is broken at the moment, as [reported on the forum](https://forum.nengo.ai/t/on-and-off-error-signal-neurons-of-ensemble-a-voltage-slice-none-5-none-shape-5/417/1). I'm not sure when that started, but it seems to be an issue with voltage re-using the Value plot infrastructure in JavaScript, but not Python. This should be done better, and it is in the refactoring, but for the time being this PR fixes the voltage plot crash.
> Fix crash with voltage graph

- nengo_gui/server.py
Add the content length field to the header as otherwise certain clients might not read all data and prevent an empty line (effectively ending the headers) when no cookies are set.
> Fixes to the HTTP response headers

- CHANGES.rst
- nengo_gui/components/netgraph.py
- nengo_gui/static/components/netgraph.css
- nengo_gui/static/components/netgraph_conn.js
- nengo_gui/tests/test_netgraph.py
This is a first implementation of #598.
I've split the code into four small commits, I think it makes most sense to go through these those independently when reviewing.
To summarise:
* *Commit 1*: Is the entire server-side implementation. Adds the connection `kind` to the `info` structure. This should be fairly tidy, and I've added some unit-tests here.
* *Commit 2*: Is a essentially a two-line change to the Python code adding the `kind` as a `class` and some changes to the CSS for adapting stroke and colour according to the `kind`. Furthermore, I changed the marker symbols for non-normal connections (inspired by what I usually end up using when I manually draw these diagrams in Inkscape, see [1]; it's trivial to change that to something else), though I did not touch the marker symbol …
> Connection types

- nengo_gui/guibackend.py
This is another security issue. By providing paths like `/static/../__init__.py` it was possible to access arbitrary files on the file system. In `master` this requires at least authentication, but in #921 I'm removing the constraint because the favicon should be available without login and we might want to use some of the style sheets on the login page at some point.
> Do not allow access to resources outside of static.

- nengo_gui/guibackend.py
This simplifies the implementation of how session IDs are generated which was needlessly complicated. It also actually ties sessions to client IPs (I suppose that was what the initial session ID generation was supposed to do, but did not actually do).
> Actually tie sessions to client

- CHANGES.rst
- nengo_gui/guibackend.py
- nengo_gui/main.py
- nengo_gui/nossl.py
- nengo_gui/server.py
Some versions of Python do not support ssl (c.f. https://techglimpse.com/install-python-openssl-support-tutorial/ ).  Currently, those versions of Python cannot run nengo_gui.  Furthermore, sometimes we may want to run nengo_gui remotely without ssl (for example, if we want to run nengo_gui on an embedded device that does not have ssl or a screen).  
This PR does two things.  First, it adds a fallback for when `import ssl` fails.  Second, it adds an `--unsecure` option which lets people explicitly turn ssl security off.
> Added --unsecure option for bypassing ssl

- nengo_gui/static/components/netgraph.css
- nengo_gui/static/components/netgraph_conn.js
The addition of coloured lines for different connections missed the special case of recurrent inhibitory connections.  Here's what it looks like now:
This PR changes that to
> Fix rendering of recurrent inhibitory connections

- CHANGES.rst
- nengo_gui/main.py
Here's an attempt at #203.  It should let you select a browser when starting nengo, so you can do something like  `nengo --browser firefox`.  It uses whatever browsers are registered with python (see https://docs.python.org/2/library/webbrowser.html for a list).
However, it doesn't seem to work on Windows for anything other than `windows-default`, and I haven't seen a good way to figure out what browsers are available (to give a useful error message).  But, I figured I would post the PR and see if it works for other people.
> Control which browser is used

- CHANGES.rst
- nengo_gui/components/pointer.py
- nengo_gui/components/spa_plot.py
- nengo_gui/components/spa_similarity.py
This adds basic support for `nengo_spa`, but breaks support for `nengo.spa` (note the dot instead of underscore). There might still be things that do not work properly and before a merge the complete SPA related code needs to be gone through and checked.
I think there are slightly to many differences to conveniently support both SPA versions. With some refactoring this might be more realistic, but that also requires more effort and it migth be better to wait for the refactored frontend #806.
Ultimately, I expect these classes to move to `nengo_spa`, but this requires the plugin structure to be in place which I probably won't tackle before the frontend refactoring is done either.
> Basic support for nengo_spa.

- nengo_gui/config.py
- nengo_gui/ipython.py
- nengo_gui/page.py
Fixes the access to the authentication token that has changed and fixes #846 by not using the editor saved in the config (and no longer saving the editor to the config at all). Instead the editor from the page settings will always be used.
Relying on the config can cause problems. For instance, when the config was writting by the standard GUI with ACE editor, it will load the ACE editor also when reusing that config within IPythonViz. But the editor needs to be deactivated in IPythonViz to have it work properly (the editor sends empty code that gets compiled and is then used instead of the actual model passed to IPythonViz).
> Ipythonviz fixes

- nengo_gui/static/modal.css
- nengo_gui/static/modal.js
- nengo_gui/static/top_toolbar.js
Addresses #910.
The solution is a bit of a hack. The offending checkbox should probably
be completely removed or disabled if there is no editor (at the moment
it can be toggled, but won't have any effect). Also the if-statements
introduced in this commit are a bit of a hack. There is probably some
better way to address this without the repeated checking whether
Nengo.ace is defined. However, it might make sense to wait for the
completion of the frontend refactoring before addressing this.
> Allow configure dialog to open without editor.

- nengo_gui/server.py
At the moment, we don't handle a full socket gracefully.  This mostly comes up if you have a large complex htmlview, which ends up breaking horribly once everything fills up.
I still need to put together a nice test, but here's a fix (this was reported in #813 )
> Fix resource unavailable bug

- CHANGES.rst
- nengo_gui/static/side_menu.css
- nengo_gui/static/side_menu.js
- nengo_gui/templates/page.html
Fixes #966.
Moved the filemenu into the `vmiddle` container to be able to inherit its height instead of doing height calculations with magic numbers. Also allowed to remove some `on_resize` JS code.
> Fix height of filemenu.

- CHANGES.rst
- nengo_gui/components/pointer.py
Fixes #970.
This is only a hotfix preventing a complete crash of the GUI. The
functionality to override the output value for Transcode modules is
still not working with this even though the context menu suggests
otherwise. In the future, values should be overwritten in the same
way as we do for nodes.
> Prevent failure for SPA Transcode plots.

- CHANGES.rst
- nengo_gui/server.py
This should fix #974.
If `'localhost'` is given as the server address, we retrieve the associated network addresses to listen on with `getaddrinfo`. For me this returns the IPv4 address `127.0.0.1` and IPv6 address `::1`. But on at least one system (see #974) the link-local address `fe80::1%lo0` was returned to. I'm not sure whether one cannot bind to that address in general (because the error is `EADDRNOTAVAIL`) or whether it ends up trying to bind the same adress again (because we already bound `::1`, but the error is not `EADDRINUSE`). There might be a way to filter these addresses, but my knowledge of IPv6 isn't sufficient to say for sure or come up with an implementation.
Thus, I decided to just catch the `EADDRNOTAVAIL` and `EADDRINUSE` errors and convert them to warnings. This …
> Fail gracefully if binding server to address fails

- CHANGES.rst
- nengo_gui/guibackend.py
Fixes #979.
Cookies do not differentiate between ports and are sent to all servers
on the same domain independent of the port. Thus, we append the port
to the cookie name to tell them apart.
> Fix shared session ID across ports.

- CHANGES.rst
- nengo_gui/completion.py
- nengo_gui/guibackend.py
This should ensure thread safety, but might not give the best
performance. It might be possible to skip processing of some
requests if too many arrive in a short interval instead of processing
all of them with a delay once the lock becomes available for each
request.
Addresses #975.
> Acquire lock when using Jedi

- nengo_gui/static/components/netgraph_conn.js
Since connections no longer use SVG the 'line' object but
a generic 'path' instead, the attributes 'x1', 'y1', 'x2',
'y2' no longer exist.
Instead of trying to parse the SVG attributes, just ask the
browser for the correct bounding box.
Fixes #1014
> Fix bounding box computation for connections

- CHANGES.rst
- nengo_gui/components/netgraph.py
- nengo_gui/page.py
- nengo_gui/static/hotkeys.js
This lets you create keyboard controls in the gui.  All keyup/down events are sent back to the server, and we keep track of which ones are currently down.  You can access this information via a new magic variable ```__page__```, which gives you the current `nengo_gui.page.Page` object.
As a simple example, this lets you do this:
```
def ctrl_node(t):
if 'w' in __page__.keys_pressed:
return 1
elif 's' in __page__.keys_pressed:
return -1
return 0
stim = nengo.Node(ctrl_node)
```
We keep track of both the `keys_pressed` and the `key_codes_pressed`, so both are available.
It should be noted that this is a very different approach to doing interaction with Nodes than was done in #727.  This is, I think, simpler, but it does mean that we're always tracking keyup/down info.
> Allow Nodes to use the keyboard state

- CHANGES.rst
- nengo_gui/components/sim_control.py
- nengo_gui/guibackend.py
- nengo_gui/page.py
The idea here is to allow people to write functions that will automatically get called by nengo_gui at various different times.  In particular, nengo_gui will look for functions with the following names:
- `def on_step(sim)`: called every simulation time step
- `def on_start(sim)`: called just before the first time step, after the user presses the Play button
- `def on_pause(sim)`: called when the pause button is pressed
- `def on_continue(sim)`: called when the Play button is pressed after a pause
- `def on_close(sim)`: called when the page is closed
In each case, the active Simulator object is passed in as the only argument.
There are two main use cases where I've found this handy.  First, if the Nengo model is controlling a robot, it is *extremely* useful to be able to send a …
> Adding event hooks for the GUI

- CHANGES.rst
- nengo_gui/components/slider.py
The current `master` version of nengo causes nengo-gui to break if you run a model and have a slider.
Here's the commit that broke things:
https://github.com/nengo/nengo/commit/e4ac75f8cc4b140b892e765226049e393b5e07bd
(it changes the Process API, and nengo-gui uses a Process to implement the sliders)
This fix is backwards-compatible and continues to work with older nengo versions.
> Fix broken sliders given recent nengo.Process API change

- CHANGES.rst
- nengo_gui/jupyter.py
This fixes two problems:
* Newer Jupyter versions use Tornado 6 and the old code wasn't compatible to that Tornado version.
* Newer Chrome versions (and potentially other browser) check the content type of HTTP responses and the server extension would respond with two (potentially conflicting) Content-Type headers which might lead to resources not being loaded properly.
> Fix jupyter integration

- CHANGES.rst
- nengo_gui/page.py
This implements my proposal from #1000. I think this is an improvement and would enable Nengo SPA to **not** set the label for networks and give better names to SPA objects when no explicit label is given.
> Use class name of a network if it is more informative

- nengo_gui/compat.py
- nengo_gui/components/netgraph.py
- nengo_gui/components/progress.py
- nengo_gui/components/slider.py
- nengo_gui/exec_env.py
- nengo_gui/user_action.py
Previously, we were using Nengo core's Python 2/3 compatibility module, but Nengo core has dropped Python 2 support and subsequently removed `nengo.utils.compat`. Since we have not yet dropped Python 2 support, we add a `compat.py` module to handle the things that we use in Nengo GUI.
This PR is required for supporting Nengo 3.0.0. With this PR, the GUI seems to work, though I haven't done extensive testing.
> Handle Python 2/3 compat

- CHANGES.rst
- nengo_gui/gui.py
In https://forum.nengo.ai/t/trouble-with-nengo-gui/1071 a user found a bug when using the `GUI` class. This fixes it.
> Fix bug opening browser from script

- CHANGES.rst
- nengo_gui/examples/hbb_tutorials/chapter3/1-addition.py
- nengo_gui/examples/hbb_tutorials/chapter3/3-non_linear.py
- nengo_gui/examples/hbb_tutorials/chapter8/2D_decision_integrator.py
Some of the examples didn't work with Nengo 3.0 (as noticed in https://github.com/nengo/nengo-gui/issues/1023), went through all of the examples and fixed any errors that popped up.
> Update examples for Nengo 3.0

- setup.py
We're not actively maintaining this version of NengoGUI, so to avoid issues with newer versions of NengoCore, let's limit this to the last version that we know works, 3.0.0.
> Limit maximum Nengo version

- nengo_gui/compat.py
collections.Iterable was deprecated since Python 3.3, see note at the top of
https://docs.python.org/3.9/library/collections.html
Use collections.abc.Iterable instead.
Fixes #1039
> Use collections.abc.Iterable
