nengo/nengo-gui

- nengo_viz/static/main.css
> Fix cursors in Firefox.

- nengo_viz/static/lib/js/interact-1.2.4.js
This fixes some resize bugs, for example it allows to resize in
x and y direction when clicking the bottom corners which was
sometime not possible with the current stable version.
> Update interact to current development version.

- nengo_viz/static/viz.js
- nengo_viz/static/viz_sim_control.js
This allows the user to view a wider or narrower range of time,
and can help make some plots much clearer (e.g. voltage plot).
> Made time slider resizable to change time window

- nengo_viz/components/slider.py
I screwed up merging moving_sliders and lost changes to sliders.py.  Here are the changes put back in.
> Fixed lost changes in moving_slider merge

- nengo_viz/static/viz_sim_control.css
- nengo_viz/static/viz_sim_control.js
Font in time line is untouched, but was changed in `graphics_overhaul`.
> Style time bar

- nengo_viz/static/viz_netgraph.js
- nengo_viz/swi.py
Stops the websocket system from ignoring messages to the server
> Fixed dropped websocket messages

- nengo_viz/components/component.py
- nengo_viz/components/netgraph.py
- nengo_viz/server.py
- nengo_viz/static/viz_netgraph.js
- nengo_viz/static/viz_netgraph_conn.js
- nengo_viz/static/viz_netgraph_item.js
- nengo_viz/viz.py
If you open up and edit the ```__file__``` using a separate text editor, the display should update whenever you save it.
> Detect code changes

- nengo_viz/components/netgraph.py
- nengo_viz/server.py
- nengo_viz/swi.py
- nengo_viz/viz.py
The first commit (the only so far), makes the config file save no more than every 2 seconds, and only after the changes have been sent to the UI. This makes everything considerably more responsive, especially for large models like Spaun.
> Changes to increase speed and responsiveness

- nengo_viz/components/netgraph.py
This removes an overwritten variable bug and handles nested networks
> Better fix for expanding collapsed networks

- nengo_viz/static/viz.js
> look for -webkit-transform if transform undefine

- nengo_viz/server.py
I broke refreshing the page somewhere along the line.  This seems to fix it for me.
> Fixes refreshing the page

- nengo_viz/components/value.py
- nengo_viz/static/viz_2d_axes.js
- nengo_viz/static/viz_netgraph.js
- nengo_viz/static/viz_raster.js
- nengo_viz/static/viz_slider.js
- nengo_viz/static/viz_slidercontrol.js
- nengo_viz/static/viz_time_axes.js
- nengo_viz/static/viz_value.js
- nengo_viz/static/viz_xyvalue.js
- nengo_viz/templates/page.html
Eliminates all absolute sizing from components and uses relative scaling/padding/margin based on the font-size. Also, makes the text zoom with everything else.
While doing this, I refactored the components to have less code duplication.
This is based on some intermediate stage of `graphics_overhaul`.
> All is relative

- nengo_viz/static/viz_modal.js
- nengo_viz/static/viz_top_toolbar.js
The user is now prompted with a modal to confirm when they click the reset model button.
> Confirm model reset

- nengo_viz/static/viz_slidercontrol.js
> Prevent setting slider values outside of range.

- nengo_viz/static/viz_slider.js
- nengo_viz/static/viz_slidercontrol.js
> Fix sliders2

- nengo_viz/static/viz_top_toolbar.css
- nengo_viz/templates/page.html
> Putting in normal looking icons

- nengo_viz/components/sim_control.py
- nengo_viz/server.py
- nengo_viz/swi.py
- nengo_viz/viz.py
Addresses #205 
The Viz object now keeps track of a list of VizSim objects.  VizSims remove themselves from that list when they are done.
When a websocket closes, it checks that list to see if it's empty.  If it is, then it shuts down the server.
For this to work, the SimControl on the server side has been modified to send out WebSocket ping events every 2 seconds (otherwise there's no way to realize the webpage has closed).
There's no configuration option yet, but I'll add that when #208 is merged.
> Shutdown server when last webpage closes

- nengo_viz/server.py
This might fix #241 
@jgosmann could you check if this works for you?
> Added 2-second delay before server shutdown

- nengo_viz/static/viz_raster.js
- nengo_viz/static/viz_xyvalue.js
This makes the plotted line in the XY plot blue and the spike raster plots colorful.
Not sure whether this makes the spike raster plots too colorful. Maybe gradual changing colors would look better. (But will be a bit more work to implement and match to the other colors.)
> More plot colors

- nengo_viz/server.py
- nengo_viz/viz.py
And adds a message letting people know the server is starting (and where it is)
> Stops all the GET message printing

- nengo_viz/swi.py
Few changes and fixing the timeout logic.
> Timely thread shutdown 2

- .gitignore
- LICENSE.md
- nengo_viz/static/lib/js/validator.js
- nengo_viz/static/viz_modal.css
- nengo_viz/static/viz_modal.js
- nengo_viz/static/viz_pointer.js
- nengo_viz/static/viz_slider.js
- nengo_viz/static/viz_value.js
- nengo_viz/static/viz_xyvalue.js
- nengo_viz/templates/page.html
This was branched off of modal-inputs. It validates user input before allowing the input to be submitted, greying things out, providing error messages, etc.  Right now, it will wait 5s before providing any error messages (or provides them immediately on hitting return).  The default was 500ms, but error messages are pretty much guaranteed to show up, and don't seem relevant til you hit return.  (To submit the form, you have to click on 'ok' or hit return when 'ok' is selected (2 tabs away from the input field).)  I wondered about having 'return' submit the form, but haven't implemented that (it might conflict with the validation).
> Modal validation

- nengo_viz/viz.py
> Declare VizException.

- nengo_viz/static/viz_netgraph_item.js
As discussed in #268 we should do this and see how we feel about it on Thursday
> Swapped corner styles for Node and Network

- nengo_viz/static/viz_netgraph.js
Should make it the same as on Google Maps.
Fixes #258.
> Invert scroll/zoom direction.

- nengo_viz/static/viz_sim_control.js
> Time bar now redraws on resizing

- nengo_viz/static/viz_slidercontrol.js
> Remove middle click functionality from slider.

- nengo_viz/static/viz_sim_control.js
> Increase time slider min width.

- nengo_viz/static/main.css
- nengo_viz/static/viz_sim_control.css
- nengo_viz/templates/page.html
3rd attempt to fix the Firefox cursor.
Hopefully, this time it will work and stay in working condition.
> Fix Firefox cursor

- nengo_viz/components/sim_control.py
- nengo_viz/disposable_js.py
- nengo_viz/static/viz_modal.css
- nengo_viz/static/viz_modal.js
- nengo_viz/static/viz_netgraph.js
- nengo_viz/static/viz_pointer.js
- nengo_viz/static/viz_slider.js
- nengo_viz/static/viz_top_toolbar.css
- nengo_viz/static/viz_top_toolbar.js
- nengo_viz/static/viz_value.js
- nengo_viz/static/viz_xyvalue.js
- nengo_viz/viz.py
This allows the user to turn on/off scaling of fonts with zoom.  It also allows defining a % of base for the font size.  This addresses #113
> Font scaling options

- nengo_viz/components/action.py
> properly handling undo of creating a duplicate slider

- CONTRIBUTORS.md
We have a bunch of new contributors that haven't signed the CONTRIBUTORS.md file. We need to do this before releasing. Below are the people that I think have to be added; if you're on this list please make a commit adding yourself to CONTRIBUTORS.md on this branch.
ping @jgosmann @xchoo
> Add yourself to CONTRIBUTORS.md

- nengo_viz/server.py
> Fixed shutting down with open connections

- nengo_viz/components/__init__.py
- nengo_viz/components/value.py
- nengo_viz/components/voltage.py
- nengo_viz/static/viz_netgraph_item.js
- nengo_viz/static/viz_value.js
Here's a first stab at a voltage plot. I tested it on `basic.py`, and though the output looks a little funny, it's actually correct (I checked it with plotting directly using matplotlib). The funniness is due to the filtering; maybe we want to reduce or turn off the filtering for voltage plots?
> Voltage plots

- nengo_viz/static/viz_sim_control.js
> Do not propagate space keydown from button.

- nengo_viz/swi.py
> Use signal handlers for shutdown confirmation.

- nengo_viz/swi.py
Am I the only one reading documentation?
[socket.send](https://docs.python.org/3/library/socket.html#socket.socket.send):
> Applications are responsible for checking that all data has been sent; if only some of the data was transmitted, the application needs to attempt delivery of the remaining data.
Addresses the problems experienced in #152.
> Make sure all data is sent.

- nengo_viz/swi.py
This should resolve the performance issues mentioned in #306.
> Poll as fast as possible when sending data.

- nengo_gui/static/main.css
> Fix white bar at bottom.

- nengo_gui/static/sim_control.css
> Fix scrolling of whole document.

- nengo_gui/static/netgraph.js
> Use correct frame of reference for zooming.

- nengo_gui/swi.py
> Only register signals in interactive mode.

- nengo_gui/static/netgraph.js
realized that even when hidden the minimap was doing all the calculations etc, so set it such that the rescaling and resizing only happens when minimap is turned displayed.
> only update minimap if displayed

- nengo_gui/static/menu.js
Fixes #332.
Better fix than #335, I think.
> Fix the position of the menu.

- nengo_gui/server.py
> Do not shutdown server too early in IPy notebook.

- nengo_gui/examples/basics/2d_representation.py
- nengo_gui/examples/basics/addition.py
- nengo_gui/examples/basics/combining.py
- nengo_gui/examples/basics/communication_channel.py
- nengo_gui/examples/basics/ensemble_array.py
- nengo_gui/examples/basics/inhibitory_gating.py
- nengo_gui/examples/basics/many_neurons.py
- nengo_gui/examples/basics/multiplication.py
- nengo_gui/examples/basics/single_neuron.py
- nengo_gui/examples/basics/squaring.py
- nengo_gui/examples/basics/two_neurons.py
Here are the same examples from old nengo_gui, but cleaned up a bit for the new nengo_gui.
> Added basic examples from old nengo_gui

- nengo_gui/components/pointer.py
Fixed Python3 compatibility issue with the pointer graph.
Addresses issue #367.
> Fixed Python3 compatibility issue with the pointer graph.

- nengo_gui/components/netgraph.py
> Fixed attempt to shortcut 'or' in the wrong direction

- nengo_gui/grandalf/layouts.py
There were some more Python 3 issues in Grandalf. Fixed 'em!
I'm going to speedy merge this and cut a 0.1.3 release, as this will come up when doing SPA models in Python 3. Actually it probably has already come up and people were just okay not doing autolayout... but in any case, this should improve things.
> Fix more Python 3 issues in Grandalf

- nengo_gui/viz.py
This allows scripts in the directory with the file being loaded
to be imported. Fixes #379.
> Add load file directory to sys.path

- nengo_gui/components/value.py
- nengo_gui/components/voltage.py
- nengo_gui/components/xyvalue.py
> Ensure stored dimension values are ints

- nengo_gui/static/2d_axes.js
- nengo_gui/static/modal.js
- nengo_gui/static/netgraph.js
- nengo_gui/static/slider.js
- nengo_gui/static/top_toolbar.js
- nengo_gui/static/viewport.js
Added an option in the configure modal to choose between having fixed aspect ratio objects on resizing of the canvas or not (e.g. when you open/close the editor).
> Resize options

- nengo_gui/server.py
- nengo_gui/viz.py
> Reprocess the script when resetting the page

- nengo_gui/static/raster.js
This is *much* faster.  Thank you to Roland Fernandez for the suggestion!
Addresses #394
> use a single SVG path for rasters

- nengo_gui/static/netgraph_item.js
> Fix resize.

- nengo_gui/components/ace_editor.py
- nengo_gui/components/netgraph.py
- nengo_gui/monkey.py
- nengo_gui/static/ace.css
- nengo_gui/static/ace.js
- nengo_gui/viz.py
This console shows both the stack trace (if there's an error) and anything printed to stdout.  This means you can do things like:
```python
print 'hello world'
help(model)
```
The console is resizable by dragging
> Added console below text editor

- nengo_gui/static/slider.js
- nengo_gui/static/value.js
- nengo_gui/static/xyvalue.js
This fixes the problem with modals in #441, but it also highlighted a problem with margins on graphs, which I've posted as another problem in #450, but that shouldn't block these changes.
> Fixes #441

- nengo_gui/static/value.js
Redraws the plot so lines are in their correct spot as soon as set range is finished
Regards #267
> Redraw plot

- nengo_gui/static/ace.css
- nengo_gui/static/ace.js
- nengo_gui/static/main.css
- nengo_gui/static/netgraph_item.js
- nengo_gui/templates/page.html
Fixes #422.
Makes some changes to the layout (using flex layout for editor and console) to have the browser handle the size calculations. Hope this doesn't break anything else.
> Fix resize

- nengo_gui/static/main.css
- nengo_gui/static/nengo.js
Fixes https://github.com/nengo/nengo_gui/pull/445#issuecomment-121063929
> Fix graphs appearing on top of editor.

- nengo_gui/components/sim_control.py
- nengo_gui/static/sim_control.js
Displayed time now goes to 0 upon reset press
Gear no longer spins on reset press
Only 1 click required to rebuild/re-play 
Fixes #467
> Fix Reset Button bugs

- nengo_gui/static/modal.js
- nengo_gui/static/sim_control.js
When the simcontrol websocket closes, warning modal is displayed.
User is prompted to restart server and refresh page 
In regards to #349
> disconnection warning with modal

- examples/basic.py
- nengo_gui/static/slidercontrol.js
Stop a moving slider by clicking on the associated guideline
Fixes #214
> Stop moving sliders easily

- nengo_gui/static/slider.js
> Multiple slider jumping bug, described in #493

- nengo_gui/static/sim_control.js
> less harsh red

- nengo_gui/components/sim_control.py
- nengo_gui/exec_env.py
- nengo_gui/page.py
- nengo_gui/static/sim_control.js
Exceptions thrown during the build process and when running the model should now be caught by nengo_gui and displayed to the user.
> Handle build and run errors

- nengo_gui/static/ace.css
- nengo_gui/static/ace.js
I believe this will fix the scrolling problem encountered in Chrome 44 (See issue #499)
If people could test it out on their browsers, that would be great!
> Fix editor scrolling problem (#499)

- nengo_gui/static/netgraph.js
> switched to clientx from layerx

- nengo_gui/exec_env.py
- nengo_gui/page.py
As pointed out in #512 we broke the IPython integration again.  This fixes it.
> Fix broken ipython

- nengo_gui/components/sim_control.py
- nengo_gui/exec_env.py
> Fix backend selector in IPython notebook.

- nengo_gui/static/menu.css
- nengo_gui/static/menu.js
This solution moves the menu to keep it on screen in a way that I hope is non-offensive to people. :P
Fixes #373
> fix menu off screen

- nengo_gui/gui.py
- nengo_gui/swi.py
Need this for setting up `nengo_gui` for testing with Selenium
> Pass interactive server argument properly

- nengo_gui/static/ace.js
- nengo_gui/static/components/component.js
- nengo_gui/static/components/netgraph.js
- nengo_gui/static/components/pointer.js
- nengo_gui/static/components/raster.js
- nengo_gui/static/components/slider.js
- nengo_gui/static/components/slidercontrol.js
- nengo_gui/static/components/time_axes.js
- nengo_gui/static/components/value.js
- nengo_gui/static/components/xyvalue.js
- nengo_gui/static/hotkeys.js
- nengo_gui/static/menu.js
- nengo_gui/static/nengo.js
- nengo_gui/static/sim_control.js
- nengo_gui/static/top_toolbar.js
Removed obsolete functions that weren't being used any more.
Added comments that help to understand how functions interact.
Arranged functions in a more logical manner.
Fix #519
> Simple Code maintenance

- nengo_gui/components/netgraph.py
- nengo_gui/modal_js.py
- nengo_gui/static_plots.py
> Got rid of disposable_js

- nengo_gui/static/ace.js
I'm rushing through this fix, as right now the editor is broken in master (it doesn't execute the script as you type)
> Fix broken editor due to refactoring in beb6638

- nengo_gui/static/modal.js
Fixes #421.
Not tested on a Mac yet.
> Use ⌘ in shortcut help box on Macs.

- nengo_gui/disposable_js.py
- nengo_gui/static/modal.js
> Add labels tuning curves

- nengo_gui/components/netgraph.py
- nengo_gui/page.py
> Rebuild Components correctly for collapsed Networks

- nengo_gui/components/__init__.py
- nengo_gui/components/netgraph.py
- nengo_gui/components/pointer.py
- nengo_gui/components/tests/test_pointer.py
- nengo_gui/components/tests/test_value.py
- nengo_gui/components/value.py
- nengo_gui/static/components/netgraph_item.js
Before regular SPA options were given which would crash the simulation if chosen.
Resolves #559
> Added plot for Compare networks

- nengo_gui/gui.py
- nengo_gui/page.py
- nengo_gui/server.py
Fixes #486
Windows doesn't like finding a relative path from
one drive to another
> Resolves windows drive path problems

- nengo_gui/components/netgraph.py
- nengo_gui/static/components/netgraph.js
Two errors were happening with the thalamus routing:
- A JavaScript error was being thrown about labels
- #563 
This pull request resolves both those issues
> Fixed thalamus routing switch errors

- nengo_gui/namefinder.py
> Fixed variable name error

- nengo_gui/components/component.py
- nengo_gui/components/tests/test_component.py
As discussed in other pull requests.
> Give warning on bad use of config system

- nengo_gui/namefinder.py
> Fix namefinder

- nengo_gui/components/spa_similarity.py
- nengo_gui/static/components/spa_similarity.js
- nengo_gui/static/nengo.js
Continuing with the process of carving out smaller pull requests out of my monster pull requests, here are all the little fix-ups to the SPA similarity plot.
> Fix various issues with SPA similarity plot

- nengo_gui/config.py
Used for saving legend_labels that are set by the user
> Added ability to add list and dict to config

- .jscs.json
- docs/codeflow.rst
- docs/dev_guide.rst
- docs/getting_started.rst
- docs/index.rst
- docs/workflow.rst
- nengo_gui/config.py
- nengo_gui/namefinder.py
- nengo_gui/page.py
- nengo_gui/static/modal.js
- nengo_gui/static/nengo.js
I'm creating another branch for all the little problems I find while editing the code so that I don't clog up the other pull requests.
> GUI style and docs fixups

- nengo_gui/components/xyvalue.py
- nengo_gui/static/components/2d_axes.js
- nengo_gui/static/components/component.js
- nengo_gui/static/components/time_axes.js
- nengo_gui/static/components/xy_axes.js
- nengo_gui/static/components/xyvalue.js
- nengo_gui/templates/page.html
Should resolve #551 , #363 and #271
> Solve issues with XY plots

- nengo_gui/components/sim_control.py
- nengo_gui/components/spike_grid.py
- nengo_gui/components/xyvalue.py
> Added self.node and self.conn to __init__

- nengo_gui/static/sim_control.css
- nengo_gui/static/sim_control.js
Addresses #659.  Build icon fully disabled during build.
> correct disabling of building icon

- nengo_gui/static/sim_control.js
> stopping sim control from stealing all of the events

- nengo_gui/static/hotkeys.js
> disabling backspace navigation

- nengo_gui/static/components/pointer.js
Addresses issue #388 by shifting and rescaling the semantic pointer cloud.
> Pointer cloud fixed to not overlap with label

- nengo_gui/components/raster.py
- nengo_gui/components/sim_control.py
- nengo_gui/components/spike_grid.py
- nengo_gui/components/xyvalue.py
- nengo_gui/static/ace.css
- nengo_gui/static/main.css
> Enable console text selection

- nengo_gui/static/components/netgraph.css
- nengo_gui/static/components/netgraph.js
- nengo_gui/static/modal.js
- nengo_gui/static/top_toolbar.js
- nengo_gui/templates/page.html
Opening this PR to notify folks I'm working on #10 . Still work in progress!
Exporting to SVG works but the XML ignores CSS so the exported images look crappy, working on embedding CSS properly.
> Export to SVG/PDF

- nengo_gui/components/netgraph.py
- nengo_gui/components/slider.py
Fixes passthrough nodes to not display NaN and allow you to manipulate them.  See discussion in #423
> passthrough nodes now have working sliders

- nengo_gui/static/data_to_csv.js
- nengo_gui/static/modal.js
- nengo_gui/static/top_toolbar.js
- nengo_gui/templates/page.html
- nengo_gui/tests/test_data_to_csv.py
Adds a button to the toolbar that allows users, to download the data from the graphs as a well formatted csv.
> Simdata download

- nengo_gui/ipython.py
And another tiny little bug fix that allows IPythonViz to run on Python3
> Fixed IPythonViz on Python3

- nengo_gui/components/netgraph.py
And another Python3 fix.  This one solved the problem that when people change something about a model, it doesn't update the netgraph or plots.
> Fixed list concatenation for Python3

- nengo_gui/components/raster.py
- nengo_gui/static/components/raster.js
This adds a right-click menu option to set the number of neurons shown in a raster plot.  This value is saved in the ```.cfg```.
Also, instead of only showing the first N neurons, the raster plot shows neurons evenly spaced across the ensemble.  So if you have an ensemble of 11 neurons and only show 3 of them, you will get neurons 0, 5, and 10.
> Set number of neurons in raster plot

- nengo_gui/components/value.py
- nengo_gui/static/components/value.js
- nengo_gui/tests/test_basic_functionality.py
The value plots used to have a fixed filter of 0.01s.  This adds an option to the right-click menu to change the synaptic filter time constant.
> Adjust synaptic filter on value plots

- nengo_gui/static/hotkeys.js
- nengo_gui/static/modal.js
> Add hotkey ctrl-s to save file.

- CONTRIBUTORS.rst
Signing the Contributor Assignment Agreement so my (other) pull
request can be merged.
> Sign Contributor Assignment Agreement for Andreas Stöckel

- nengo_gui/components/pointer.py
- nengo_gui/static/components/pointer.js
This can be handy for stopping the text from getting too large.
> Set maximum font size for pointer clouds

- nengo_gui/components/netgraph.py
Some little changes I made to `netgraph.py` to make the code more readable
> Fixed syntax and formatting in netgraph.py

- nengo_gui/main.py
The `nengo` command ignored the `--port` argument. This is fixed here. Also, if no port is provided and 8080 is not available, it will increase the port number until an available port is found. This is consistent with the Jupyter notebook behaviour and usually pretty convenient. It makes it also less important to be able to pass arguments to nengo_gui through pytry as it allows to start multiple GUI instances with pytry.
> Fix port selection.

- nengo_gui/static/top_toolbar.css
- nengo_gui/templates/page.html
I think a link in the top toolbar to the forum would be helpful.  I thought about also adding an API link, but I think getting people to the forum is more directly useful.
> Added link to forum

- nengo_gui/page.py
- nengo_gui/seed_generation.py
This means that if you do set the seed for the top-level
Network in your model, adding or removing graphs will not
affect the seed for the Ensembles in your model.
This should fix #855
> Generate seeds before adding graph components

- nengo_gui/static/lib/js/interact-1.2.6.js
- nengo_gui/templates/page.html
PR #881 implements view panning with the middle mouse
button. This required a tiny patch to interactjs.
Fortunately, the corresponding change is already part
of the current interactjs version.
This PR has been filed independently of #881 in order
to facilitate separate testing of the new interactjs
version and #881.
> Update interactjs to version 1.2.6

- CHANGES.rst
- nengo_gui/static/hotkeys.js
Added a few lines of code that allow using backspace in the search box. Should resolve #821.
> Enable backspace in searchbox.

- nengo_gui/static/ace.js
> Use post method for autocompletion.

- nengo_gui/guibackend.py
- nengo_gui/page.py
> Minor style fixes

- CHANGES.rst
- nengo_gui/components/netgraph.py
> Escape labels.

- CHANGES.rst
- nengo_gui/static/components/raster.js
An update to the raster plot so you can listen to the spikes of neurons you hover over.
> Spike sounds

- CHANGES.rst
- nengo_gui/jupyter.py
**Motivation and context:**
I was making a notebook for NengoFPGA that needed the embedded GUI and realized the constrcutor does not allow you to set the backend. See #1005 for details.
**How has this been tested?**
Tested a simple network in a notebook. I tried setting various backends to ensure it was correctly set in `page_settings` and I ran a network successfully using the `nengo_fpga` backend.
eg.
``` python
import numpy as np
import nengo
from nengo_gui.jupyter import InlineGUI
from nengo_fpga.networks import FpgaPesEnsembleNetwork
with nengo.Network() as model:
input_node = nengo.Node(lambda x: np.sin(x*10), label='input signal')
pes_ens = FpgaPesEnsembleNetwork(
'de1', n_neurons=100, dimensions=1, learning_rate=0,
label='ensemble')
nengo.Connection(input_node, pes_ens.input) …
```
> Add backend to InlineGUI constructor
